### ISSUE TITLE
Inclusion of Jakarta NoSQL in Jakarta EE 11?

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/platform#660]
Use this issue to discuss whether Jakarta NoSQL is a candidate for inclusion in Jakarta EE 11.

[AB#29](https://dev.azure.com/jakarta-ee-azdo/7cf9a9d3-9854-41e0-9a66-99506a9ed874/_workitems/edit/29)

**Comment by starksm64** [comment]
Red Hat will oppose this for at least two reasons. 1. we don't have users asking for this. To be part of a platform or profile there needs to be demonstrated user demand. 2. The current approach is introducing a new query language to try to abstract across implementations. This is not what users currently do, and results in a weaker feature. We looked at using the JPA API and JPQL in our https://hibernate.org/ogm/ approach in addition to exposing the native query capabilities.

**Comment by keilw** [comment]
> Hibernate OGM is not maintained anymore.

@starksm64 Why are you opposing something new that's maintained?
There is no new query language in Jakarta NoSQL, aside from the ability to use those of a particular NoSQL DB like

- CQL (Cassandra)
- Cypher (Neo4J)
- etc.

It seams reasonable for NoSQL to wait for Jakarta Data due to upstream dependencies, potentially data, although depending on what's otherwise decided between Jakarta EE and MicroProfile, MP Config may be a viable alternative, especially for the compatible implementation JNoSQL.

**Comment by amoscatelli** [comment]
I think NoSQL is a perfect candidate.
It will bring a rich abstracted API (KeyValue, Document, Column, Graph) over NoSQL databases.
