### ISSUE TITLE
Remove the optional specifications from the platform spec

### ISSUE THREAD

**Issue by Emily-Jiang** [jakartaee/platform#895]
Based on the decision of not including optional specs, this specification needs to get the optional specs removed.

**Comment by scottmarlow** [comment]
@edburns should this issue be assigned to you?  

For reference (3rd item) from https://jakarta.ee/specifications/platform/11/:

> Removals, deprecations or backwards incompatible changes
> -    Prune ManagedBeans
> -    Remove all use of SecurityManager
> -    Remove all optional specifications

Related question is whether `Remove all optional specifications` refers to removing both:
  - Optional EE specifications (will need an exact list of EE specifications that will be removed I think).
  - And optional features that are part of required EE specifications.  If we intend to remove these also, we will need a specific list of which features are removed.

**Comment by jhanders34** [comment]
@Emily-Jiang do the changes that I did in https://github.com/jakartaee/platform/pull/909 address this issue for you?  If so, I believe this issue can be closed out.

To answer Scott Marlow's question, optional specifications and optional features that are part of required specifications can still be implemented by a vendor, but if not explicitly stated as being required by the platform or profile specifications.  So those optional features in required specs just need to have TCK options to not run them in order to not require the vendor to implement optional features that are no required by the platform / profile.
